"""The golden set: the questions, their gold chunks, and the rules they obey.

A question is not golden because someone wrote it down. It is golden because
someone also wrote down **which chunks answer it**. Without ``gold_chunks``
there is no nDCG, no MRR and no hit-rate - only an LLM's opinion of whether the
answer looked nice, which measures the judge rather than the retriever.

Two consistency rules are enforced rather than trusted:

* **Answerable and unanswerable are structurally different.** An unanswerable
  question has no gold chunks and no reference answer; an answerable one has
  both. A case that claims to be unanswerable while carrying gold chunks is a
  labelling bug that would poison both the retrieval metrics and the abstention
  metric at once.

* **Gold may not come from a model under comparison.** If the reference answers
  were generated by the same model the benchmark is scoring, reference-match
  scoring rewards *imitating that model* rather than being right, and the
  incumbent wins by construction. ``check_provenance`` makes that a hard error.
"""

from __future__ import annotations

import json
from collections import Counter
from enum import StrEnum
from pathlib import Path
from typing import Self

from pydantic import BaseModel, ConfigDict, Field, ValidationError, model_validator

__all__ = [
    "GoldenCase",
    "GoldenSetError",
    "QueryClass",
    "check_provenance",
    "class_distribution",
    "load_golden_set",
]


class GoldenSetError(ValueError):
    """Raised when the golden set is malformed or internally inconsistent."""


class QueryClass(StrEnum):
    """The four classes the golden set is stratified across.

    Stratification is not decoration: a single overall mean can hide a strategy
    that wins two classes and loses two, which is precisely the effect this
    benchmark exists to surface.
    """

    SINGLE_HOP = "single_hop"
    MULTI_HOP = "multi_hop"
    SUMMARISATION = "summarisation"
    UNANSWERABLE = "unanswerable"


class GoldenCase(BaseModel):
    """One question, with everything needed to score any arm's answer to it."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    id: str
    query_class: QueryClass = Field(alias="class")
    question: str = Field(min_length=1)
    gold_chunks: list[str] = Field(default_factory=list)
    answer: str | None = None
    should_abstain: bool = False
    #: Where the ground truth came from: ``dataset``, ``human``, or
    #: ``model:<id>``. Recorded so ``check_provenance`` can refuse to score a
    #: model against its own output.
    gold_provenance: str = "dataset"

    @model_validator(mode="after")
    def _answerability_is_consistent(self) -> Self:
        # Check the class/flag agreement FIRST. It is the root cause whenever it
        # is violated, and the structural checks below would otherwise fire on
        # the symptom and report a misleading reason.
        if self.query_class is QueryClass.UNANSWERABLE and not self.should_abstain:
            raise ValueError(
                f"case {self.id!r} is in the unanswerable class but should_abstain is False"
            )
        if self.should_abstain and self.query_class is not QueryClass.UNANSWERABLE:
            raise ValueError(
                f"case {self.id!r} sets should_abstain but is classed "
                f"{self.query_class.value!r}, not 'unanswerable'"
            )

        if self.should_abstain:
            if self.gold_chunks:
                raise ValueError(
                    f"case {self.id!r} is marked unanswerable but carries "
                    f"{len(self.gold_chunks)} gold chunk(s); one of the two labels is wrong"
                )
            if self.answer is not None:
                raise ValueError(
                    f"case {self.id!r} is marked unanswerable but carries a reference answer"
                )
        else:
            if not self.gold_chunks:
                raise ValueError(
                    f"case {self.id!r} is answerable but has no gold_chunks - "
                    f"retrieval metrics would be uncomputable for it"
                )
            if self.answer is None:
                raise ValueError(f"case {self.id!r} is answerable but has no reference answer")

        if len(set(self.gold_chunks)) != len(self.gold_chunks):
            raise ValueError(f"case {self.id!r} lists a gold chunk more than once")
        return self


def load_golden_set(path: str | Path) -> list[GoldenCase]:
    """Load a JSONL golden set, failing loudly on the first malformed case."""
    golden_path = Path(path)
    try:
        raw = golden_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise GoldenSetError(f"cannot read golden set {golden_path}: {exc}") from exc

    cases: list[GoldenCase] = []
    for line_number, line in enumerate(raw.splitlines(), start=1):
        if not line.strip():
            continue
        try:
            payload = json.loads(line)
        except json.JSONDecodeError as exc:
            raise GoldenSetError(f"{golden_path}:{line_number} is not valid JSON: {exc}") from exc
        try:
            cases.append(GoldenCase.model_validate(payload))
        except ValidationError as exc:
            raise GoldenSetError(f"{golden_path}:{line_number} is invalid:\n{exc}") from exc

    if not cases:
        raise GoldenSetError(f"{golden_path} contains no cases")

    ids = [case.id for case in cases]
    duplicates = sorted({i for i in ids if ids.count(i) > 1})
    if duplicates:
        raise GoldenSetError(f"{golden_path} has duplicate case ids: {duplicates}")

    return cases


def check_provenance(cases: list[GoldenCase], models_under_test: set[str]) -> None:
    """Refuse to score a model against ground truth it produced.

    Reference-match scoring against a model's own output rewards imitating that
    model rather than being right. In a comparison this is fatal: the incumbent
    looks best by construction and every rival is penalised for stylistic
    difference.
    """
    offenders = sorted(
        {
            case.id
            for case in cases
            if case.gold_provenance.startswith("model:")
            and case.gold_provenance.removeprefix("model:") in models_under_test
        }
    )
    if offenders:
        raise GoldenSetError(
            f"ground truth for {len(offenders)} case(s) was generated by a model that is "
            f"itself under test ({sorted(models_under_test)}); this scores imitation, not "
            f"correctness. Offending case ids: {offenders[:10]}"
        )


def class_distribution(cases: list[GoldenCase]) -> dict[str, int]:
    """Count cases per class, so an unbalanced set is visible before a run."""
    counts = Counter(case.query_class.value for case in cases)
    return {klass.value: counts.get(klass.value, 0) for klass in QueryClass}
